name: Python package

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install tox and any other packages
        run: pip install tox

      - name: Check for lint
        run: tox -e lint

  build:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox and any other packages
        run: pip install tox

      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py

  coverage:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install tox and any other packages
        run: pip install tox

      - name: Collect coverage data
        run: tox -e coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          # directory: ./coverage/reports/
          # env_vars: OS,PYTHON
          fail_ci_if_error: true
          # files: ./coverage1.xml,./coverage2.xml
          # flags: unittests
          # name: codecov-umbrella
          # path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
